"use client";
import {ledgerRequest,browserStorage} from '../lib/ledger-client';
import {useEffect,useState,useRef} from 'react';
import {Leaf,Plus,Minus,ChevronLeft,ChevronRight,Coins,Gem,Timer,Pencil,Trash2,X} from 'lucide-react';
type Entry={id:string;date:string;count:number;meso:number;pieces:number;price:number};
const today=()=>new Date().toLocaleDateString('sv-SE');
const fmt=(n:number)=>Math.round(n).toLocaleString('ko-KR');
const total=(e:Entry)=>e.meso+e.pieces*e.price;
const ko=(n:number)=>n>=1e8?`${(n/1e8).toLocaleString('ko-KR',{maximumFractionDigits:2})}억`:n>=1e4?`${(n/1e4).toLocaleString('ko-KR',{maximumFractionDigits:1})}만`:fmt(n);
export default function Home(){
const requestId=useRef('');
const [entries,setEntries]=useState<Entry[]>([]),[month,setMonth]=useState(''),[date,setDate]=useState(''),[count,setCount]=useState(1),[meso,setMeso]=useState(''),[pieces,setPieces]=useState(''),[price,setPrice]=useState(''),[edit,setEdit]=useState<string|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[failed,setFailed]=useState(false),[message,setMessage]=useState(''),[remove,setRemove]=useState<string|null>(null);
async function load(){setLoading(true);try{const r=await ledgerRequest();if(!r.ok)throw Error();const d=await r.json() as {entries:Entry[];price:number|null};setEntries(d.entries);setPrice(String(d.price??''));setFailed(false);}catch{setFailed(true);setMessage('기록을 불러오지 못했어요. 다시 시도해 주세요.');}finally{setLoading(false);}}
useEffect(()=>{setDate(today());setMonth(today().slice(0,7));void load();},[]);
useEffect(()=>{const c=(document as any).modelContext;if(!c?.registerTool)return;const ac=new AbortController();Promise.resolve(c.registerTool({name:'read_monthly_hunting_summary',description:'저장된 월별 사냥 횟수와 수익을 조회합니다.',inputSchema:{type:'object',properties:{month:{type:'string',pattern:'^\\d{4}-(0[1-9]|1[0-2])$'}},required:['month'],additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:any)=>{if(!input||!/^\d{4}-(0[1-9]|1[0-2])$/.test(input.month))throw Error('YYYY-MM 형식의 월이 필요합니다.');if(loading||failed)throw Error('기록을 먼저 불러와 주세요.');const rows=entries.filter(e=>e.date.startsWith(input.month));return{month:input.month,records:rows.length,count:rows.reduce((a,e)=>a+e.count,0),revenue:rows.reduce((a,e)=>a+total(e),0)};}},{signal:ac.signal})).catch(()=>{});return()=>ac.abort();},[entries,loading,failed]);
const rows=entries.filter(e=>e.date.startsWith(month)).sort((a,b)=>b.date.localeCompare(a.date));
const sum=rows.reduce((s,e)=>({meso:s.meso+e.meso,pieces:s.pieces+e.pieces,value:s.value+e.pieces*e.price,count:s.count+e.count}),{meso:0,pieces:0,value:0,count:0});
const revenue=sum.meso+sum.value,preview=Number(meso||0)+Number(pieces||0)*Number(price||0);
function reset(){requestId.current='';setEdit(null);setMeso('');setPieces('');setCount(1);setDate(today());}
async function save(ev:React.FormEvent){ev.preventDefault();if(busy)return;setBusy(true);setMessage('');const item={id:edit||(requestId.current||=crypto.randomUUID()),date,count,meso:Number(meso),pieces:Number(pieces),price:Number(price)};try{const r=await ledgerRequest({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(item)});if(!r.ok)throw Error();setEntries(p=>[...p.filter(e=>e.id!==item.id),item]);setMonth(date.slice(0,7));reset();setMessage(edit?'기록을 수정했어요.':'사냥 기록을 저장했어요.');}catch{setMessage('저장하지 못했어요. 입력한 내용은 유지됩니다. 다시 시도해 주세요.');}finally{setBusy(false);}}
async function deleteEntry(){if(!remove||busy)return;setBusy(true);try{const r=await ledgerRequest({method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:remove})});if(!r.ok)throw Error();setEntries(p=>p.filter(e=>e.id!==remove));if(edit===remove)reset();setRemove(null);setMessage('기록을 삭제했어요.');}catch{setMessage('삭제하지 못했어요. 다시 시도해 주세요.');}finally{setBusy(false);}}
function changeMonth(step:number){const [y,m]=month.split('-').map(Number);setMonth(new Date(y,m-1+step,1).toLocaleDateString('sv-SE').slice(0,7));}
const days=month?new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate():31;
const daily=Array.from({length:days},(_,i)=>rows.filter(e=>Number(e.date.slice(8))===i+1).reduce((a,e)=>a+total(e),0)),max=Math.max(...daily,1);
return <><header className="topbar"><a className="brand" href="./"><span className="brand-icon"><Leaf size={23}/></span>메이플 사냥장부<span className="brand-en">HUNTING LOG</span></a><span className="private-label">나의 사냥 기록</span></header><main><div className="heading"><div><p className="eyebrow">차곡차곡 쌓이는 사냥 수익</p><h1>오늘도, 한 소재비.</h1></div><div className="month-picker"><button aria-label="이전 달" disabled={!month} onClick={()=>changeMonth(-1)}><ChevronLeft size={19}/></button><input aria-label="조회할 월" type="month" value={month} onChange={e=>e.target.value&&setMonth(e.target.value)}/><button aria-label="다음 달" disabled={!month} onClick={()=>changeMonth(1)}><ChevronRight size={19}/></button></div></div>
<section className="stats" aria-label="월별 수익 요약"><div className="stat main-stat"><span>이달의 총 수익</span><strong>{loading?'…':ko(revenue)} <small>메소</small></strong><p>사냥 메소 + 조각 환산액</p></div><div className="stat"><span><Coins size={17}/> 사냥 메소</span><strong>{loading?'…':ko(sum.meso)} <small>메소</small></strong><p>직접 획득한 메소</p></div><div className="stat"><span><Gem size={17}/> 솔 에르다 조각</span><strong>{loading?'…':fmt(sum.pieces)} <small>개</small></strong><p>환산 수익 {ko(sum.value)} 메소</p></div><div className="stat"><span><Timer size={17}/> 누적 소재비</span><strong>{loading?'…':fmt(sum.count)} <small>회</small></strong><p>{rows.length}건의 사냥 기록</p></div></section>
<div className="workspace"><section className="panel entry-panel"><div className="panel-title"><h2>{edit?'사냥 기록 수정':'사냥 기록하기'}</h2><span className="tag">{edit?'수정 중':'NEW LOG'}</span></div><form onSubmit={save}><label>사냥 날짜<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label>소재비 횟수</label><div className="counter"><button type="button" aria-label="소재비 1회 감소" disabled={count===0} onClick={()=>setCount(c=>Math.max(0,c-1))}><Minus/></button><span><b>{count}</b> 회</span><button type="button" aria-label="소재비 1회 증가" onClick={()=>setCount(c=>Math.min(10000,c+1))}><Plus/></button></div><div className="quick"><button type="button" onClick={()=>setCount(c=>Math.min(10000,c+1))}>+1 소재비</button><button type="button" onClick={()=>setCount(c=>Math.min(10000,c+5))}>+5 소재비</button><button type="button" onClick={()=>setCount(0)}>초기화</button></div><label>사냥으로 획득한 메소<div className="unit-input"><input aria-label="사냥으로 획득한 메소" type="number" min="0" max="1000000000000" step="1" placeholder="0" required value={meso} onChange={e=>setMeso(e.target.value)}/><span>메소</span></div></label><div className="input-pair"><label>솔 에르다 조각<div className="unit-input"><input aria-label="솔 에르다 조각 개수" type="number" min="0" max="1000000" step="1" placeholder="0" required value={pieces} onChange={e=>setPieces(e.target.value)}/><span>개</span></div></label><label>조각 1개 가격<div className="unit-input"><input aria-label="조각 1개 가격" type="number" min="0" max="1000000000" step="1" placeholder="직접 설정" required value={price} onChange={e=>setPrice(e.target.value)}/><span>메소</span></div></label></div><p className="helper">가격은 기록과 함께 저장됩니다.</p><div className="estimate"><span>이번 사냥 예상 수익</span><strong>{fmt(preview)} <small>메소</small></strong></div><button className="save" disabled={busy||loading||failed} type="submit"><Plus size={18}/>{busy?'저장 중…':edit?'수정 내용 저장':'사냥 기록 저장'}</button>{edit&&<button type="button" className="cancel" onClick={reset}>수정 취소</button>}</form></section>
<div className="right-column"><section className="panel chart-panel"><div className="panel-title"><div><h2>일별 수익</h2><p>{month?`${Number(month.slice(5))}월의 사냥 흐름`:''}</p></div><div className="chart-legend"><i/>총 수익</div></div><div className="chart"><div className="chart-top">{ko(max===1?0:max)} 메소</div><div className="chart-bars" role="img" aria-label="날짜별 총 수익 막대그래프">{daily.map((v,i)=><div className="bar-col" key={i} title={`${i+1}일: ${fmt(v)} 메소`}><div className="bar" style={{height:v?`${Math.max(2,v/max*100)}%`:'0'}}/></div>)}{!rows.length&&<div className="chart-empty">첫 사냥 기록으로 이번 달을 채워 보세요.</div>}</div><div className="axis"><span>1일</span><span>{Math.ceil(days/2)}일</span><span>{days}일</span></div></div><div className="chart-footer"><span>소재비당 평균 수익</span><b>{sum.count?ko(revenue/sum.count):'—'} <small>메소</small></b></div></section>
<section className="panel records"><div className="panel-title"><h2>사냥 내역 <span className="record-count">{rows.length}</span></h2><span className="helper">기록 당시 가격 기준</span></div>{loading?<div className="empty">기록을 불러오고 있어요…</div>:failed?<div className="empty">기록을 불러오지 못했어요.<button onClick={load}>다시 시도</button></div>:rows.length?<div className="table-wrap"><table><thead><tr><th>날짜 / 소재비</th><th>사냥 메소 / 조각</th><th>총 수익</th><th><span className="sr-only">관리</span></th></tr></thead><tbody>{rows.map(e=><tr key={e.id}><td><b>{e.date.slice(5).replace('-','.')}</b><small>{e.count} 소재비</small></td><td>{ko(e.meso)} 메소<small>{e.pieces}개 × {fmt(e.price)} 메소</small></td><td className="row-total">{ko(total(e))}<small>메소</small></td><td><div className="row-actions"><button aria-label={`${e.date} 기록 수정`} onClick={()=>{setEdit(e.id);setDate(e.date);setCount(e.count);setMeso(String(e.meso));setPieces(String(e.pieces));setPrice(String(e.price));window.scrollTo({top:0,behavior:'smooth'});}}><Pencil size={15}/></button><button aria-label={`${e.date} 기록 삭제`} onClick={()=>setRemove(e.id)}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div>:<div className="empty"><span className="empty-icon"><Leaf size={26}/></span><b>아직 기록된 사냥이 없어요</b><p>사냥을 마친 뒤 메소와 조각을 기록해 주세요.</p></div>}</section></div></div>
<footer>{browserStorage() ? "이 브라우저에만 저장 · 다른 기기와 동기화되지 않음 · 브라우저 데이터 삭제 시 기록도 삭제" : "메이플 사냥장부"}<span>수익은 수수료와 소비 비용을 차감하지 않은 메소 환산액입니다.</span></footer><div role="status" className={message?'notice':''}>{message&&<>{message}<button aria-label="알림 닫기" onClick={()=>setMessage('')}><X size={16}/></button></>}</div>{remove&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="delete-title"><h2 id="delete-title">이 사냥 기록을 삭제할까요?</h2><p>삭제한 기록은 복구할 수 없습니다.</p><div><button autoFocus onClick={()=>setRemove(null)} disabled={busy}>취소</button><button className="danger" onClick={deleteEntry} disabled={busy}>삭제</button></div></section></div>}</main></>;
}
